# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('serial_no', models.CharField(max_length=10)),
                ('designated_for', models.CharField(blank=True, max_length=10)),
                ('curriculum_no', models.CharField(blank=True, max_length=20)),
                ('class_no', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('credits', models.CharField(blank=True, max_length=10)),
                ('curriculum_identity_no', models.CharField(blank=True, max_length=20)),
                ('full_half_yr', models.CharField(blank=True, max_length=10)),
                ('required_elective', models.CharField(blank=True, max_length=10)),
                ('instructor', models.CharField(blank=True, max_length=10)),
                ('instructor_url', models.TextField(blank=True)),
                ('sel_method', models.CharField(choices=[('0', 'UNKNOWN'), ('1', '不限人數，直接上網加選'), ('2', '向教師取得授權碼後加選'), ('3', '有人數限制，上網登記後分發')], default='0', max_length=10)),
                ('schedule_str', models.CharField(blank=True, max_length=20)),
                ('classroom', models.CharField(blank=True, max_length=20)),
                ('classroom_url', models.TextField(blank=True)),
                ('capacity', models.CharField(blank=True, max_length=10)),
                ('course_limits', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('syllabus_url', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('goal', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('office_hours', models.CharField(blank=True, max_length=20)),
                ('textbooks', models.TextField(blank=True)),
                ('grading', models.TextField(blank=True)),
                ('progress', models.TextField(blank=True)),
                ('course_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('loading', models.CharField(choices=[('0', 'UNKNOWN'), ('1', '輕'), ('2', '尚可'), ('3', '中等'), ('4', '中上'), ('5', '重')], default='0', max_length=2)),
                ('sweetness', models.CharField(choices=[('0', 'UNKNOWN'), ('1', '輕'), ('2', '尚可'), ('3', '中等'), ('4', '中上'), ('5', '重')], default='0', max_length=2)),
                ('stars', models.CharField(choices=[('0', 'UNKNOWN'), ('1', '輕'), ('2', '尚可'), ('3', '中等'), ('4', '中上'), ('5', '重')], default='0', max_length=2)),
                ('content', models.TextField(blank=True)),
                ('sentiment', models.CharField(default='Neutral', max_length=10)),
                ('probability', models.CharField(blank=True, max_length=20)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MON', '星期一'), ('TUE', '星期二'), ('WED', '星期三'), ('THU', '星期四'), ('FRI', '星期五'), ('SAT', '星期六'), ('SUN', '星期日')], max_length=10)),
                ('time', models.CharField(choices=[('0', '7:00-8:00'), ('1', '8:10-9:00'), ('2', '9:10-10:00'), ('3', '10:20-11:10'), ('4', '11:20-12:10'), ('5', '12:20-13:10'), ('6', '13:20-14:10'), ('7', '14:20-15:10'), ('8', '15:30-16:20'), ('9', '16:30-17:20'), ('10', '17:30-18:20'), ('A', '18:30-19:20'), ('B', '19:25-20:15'), ('C', '20:25-21:15'), ('D', '21:20-22:10')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('selected_course', models.ManyToManyField(blank=True, to='crawler.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='crawler.Schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('semester', 'serial_no')]),
        ),
    ]
